### ISSUE TITLE
linux命令中linux软件管理链接错误

### ISSUE THREAD

**Issue by here101** [dunwu/linux-tutorial#13]
博主，您们写的这个教程使我受益颇多，我从中学到了许多知识，但在学习的过程中我发现一个问题：
就点击linux命令中linux软件管理 ，跳转到的是linux硬件管理页面。我是通过搜索linux软件管理才搜索到软件管理页面的。

**Comment by dunwu** [comment]
@here101 应该不会吧，有截图吗？

**Comment by here101** [comment]
> @here101 应该不会吧，有截图吗？
这个是部署在码云上的教程，不知道github上的是不是同样的……
复现：
网址：https://turnon.gitee.io/linux-tutorial/#linux-%E5%91%BD%E4%BB%A4
点击
![图片](https://user-images.githubusercontent.com/49056220/206105377-8cbfba5a-b618-493c-acc7-8766da2b7079.png)

就会跳到
https://turnon.gitee.io/linux-tutorial/linux/cli/linux-cli-hardware.html#_1-linux-%E7%A1%AC%E4%BB%B6%E7%AE%A1%E7%90%86%E8%A6%81%E7%82%B9
![图片](https://user-images.githubusercontent.com/49056220/206105637-cd496e84-1656-4616-9359-a0270ad96ca1.png)

上去。

**Comment by dunwu** [comment]
@here101 github page 是正常的，gitee page 可能由于没有实名认证，不支持更新了
可以访问：https://dunwu.github.io/linux-tutorial/
